language: ruby
rvm: 2.5.0

env:
  - DB=mysql
addons:

  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
script: 
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec spec/
before_script:
  -'RAILS_ENV=test bundle exec rake db:create --trace'
  -mysql -e 'create database myapp_test'
bundler_args: --binstubs=./bundler_stubs