language: ruby
rvm:
  - 2.5.0
env:
  - DB=mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_install:
  - mysql -e 'CREATE DATABASE my_app_test;'
before_script:
  - mysql -e 'create database my_app_test'
bundler_args: --binstubs=./bundler_stubs