language: ruby
rvm:
  - "2.5.0"
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec
before_script:
  - psql -c 'create database daily_expense_web_test;' -U postgres
bundler_args: --binstubs=./bundler_stubs