language: ruby
rvm:
  - "2.5.0"
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec
before_script:
  - mysql -e 'create database daily_expense_web_test'
bundler_args: --binstubs=./bundler_stubs